import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(162 60% 96%)",
          100: "hsl(162 55% 90%)",
          200: "hsl(162 55% 78%)",
          300: "hsl(162 60% 60%)",
          400: "hsl(162 65% 40%)",
          500: "hsl(162 70% 25%)",
          600: "hsl(162 72% 18%)",
          700: "hsl(162 72% 14%)",
          800: "hsl(162 70% 10%)",
          900: "hsl(162 68% 7%)",
        },
        gold: {
          DEFAULT: "hsl(var(--gold))",
          dark: "hsl(var(--gold-dark))",
          light: "hsl(var(--gold-light))",
          foreground: "hsl(var(--gold-foreground))",
          50: "hsl(42 70% 97%)",
          100: "hsl(42 65% 90%)",
          200: "hsl(42 62% 80%)",
          300: "hsl(42 62% 70%)",
          400: "hsl(42 60% 60%)",
          500: "hsl(42 60% 52%)",
          600: "hsl(40 58% 42%)",
          700: "hsl(38 55% 35%)",
          800: "hsl(36 52% 26%)",
          900: "hsl(34 50% 18%)",
        },
        cream: {
          DEFAULT: "hsl(42 45% 97%)",
          50: "hsl(35 60% 99%)",
          100: "hsl(42 45% 97%)",
          200: "hsl(42 38% 93%)",
          300: "hsl(42 30% 87%)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        sans: ["Vazirmatn", "sans-serif"],
        heading: ["'Markazi Text'", "serif"],
        display: ["'Markazi Text'", "serif"],
        special: ["Lalezar", "cursive"],
      },
      fontSize: {
        "display-xl": ["clamp(3rem, 8vw, 7rem)", { lineHeight: "1.05", letterSpacing: "-0.01em" }],
        "display-lg": ["clamp(2.5rem, 6vw, 5rem)", { lineHeight: "1.1" }],
        "display-md": ["clamp(2rem, 4vw, 3.5rem)", { lineHeight: "1.15" }],
        "display-sm": ["clamp(1.5rem, 3vw, 2.5rem)", { lineHeight: "1.2" }],
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
        "30": "7.5rem",
        "34": "8.5rem",
      },
      boxShadow: {
        "gold-sm": "0 2px 8px hsl(42 60% 52% / 0.2)",
        "gold": "0 4px 16px hsl(42 60% 52% / 0.3)",
        "gold-lg": "0 8px 32px hsl(42 60% 52% / 0.35)",
        "emerald-sm": "0 2px 8px hsl(162 72% 14% / 0.15)",
        "emerald": "0 4px 16px hsl(162 72% 14% / 0.25)",
        "emerald-lg": "0 8px 32px hsl(162 72% 14% / 0.3)",
        "card": "0 1px 3px rgba(0,0,0,0.06), 0 4px 12px rgba(0,0,0,0.05)",
        "card-hover": "0 4px 24px rgba(0,0,0,0.1), 0 12px 40px rgba(0,0,0,0.07)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "gold-shimmer": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "float-gentle": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(1)", opacity: "1" },
          "100%": { transform: "scale(1.6)", opacity: "0" },
        },
        "pattern-drift": {
          "0%": { transform: "translateX(0) translateY(0)" },
          "100%": { transform: "translateX(-60px) translateY(-60px)" },
        },
        "marquee-rtl": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "gold-shimmer": "gold-shimmer 3s ease infinite",
        "float-gentle": "float-gentle 4s ease-in-out infinite",
        "pulse-ring": "pulse-ring 1.5s ease-out infinite",
        "pattern-drift": "pattern-drift 20s linear infinite",
        "marquee-rtl": "marquee-rtl 40s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
