# Generated by Django 4.2.28 on 2026-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_leader_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده به عنوان مدیر کاروان'),
        ),
        migrations.AddField(
            model_name='user',
            name='leader_bio',
            field=models.TextField(blank=True, null=True, verbose_name='معرفی مدیر کاروان'),
        ),
        migrations.AddField(
            model_name='user',
            name='messaging_apps',
            field=models.JSONField(blank=True, default=list, verbose_name='پیام\u200cرسان\u200cها'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'زایر'), ('caravan_leader', 'مدیر کاروان')], default='user', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
