# Generated by Django 4.2.28 on 2026-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caravan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departure_date', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('transportation_type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('remaining_capacity', models.IntegerField()),
                ('accommodation_type', models.CharField(max_length=200)),
                ('accommodation_distance', models.IntegerField()),
                ('manager', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('popular', models.BooleanField(default=False)),
                ('special_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
