# Generated by Django 4.2.28 on 2026-07-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carvans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caravan',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاروان', 'verbose_name_plural': 'کاروان\u200cها'},
        ),
        migrations.AddField(
            model_name='caravan',
            name='accommodation_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر اقامتگاه'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='accommodation_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام اقامتگاه'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس کاروان'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='destination',
            field=models.CharField(choices=[('mashhad', 'مشهد مقدس'), ('karbala', 'کربلای معلا'), ('hajj_umrah', 'حج/عمره'), ('qom_jamkaran', 'قم/جمکران')], default='karbala', max_length=20, verbose_name='مقصد'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='has_insurance',
            field=models.BooleanField(default=False, verbose_name='بیمه مسافرتی'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caravans/', verbose_name='تصویر کاروان'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, verbose_name='برنامه سفر'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_caravans', to=settings.AUTH_USER_MODEL, verbose_name='مدیر کاروان'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='leader_messaging_apps',
            field=models.JSONField(blank=True, default=list, verbose_name='پیام\u200cرسان\u200cهای مدیر'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='meal_breakfast',
            field=models.BooleanField(default=False, verbose_name='صبحانه'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='meal_dinner',
            field=models.BooleanField(default=False, verbose_name='شام'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='meal_lunch',
            field=models.BooleanField(default=False, verbose_name='ناهار'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='origin_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='مبدأ حرکت'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='rules',
            field=models.TextField(blank=True, verbose_name='قوانین و مقررات کاروان'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='transit_cities',
            field=models.JSONField(blank=True, default=list, verbose_name='شهرهای بین\u200cراهی'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='accommodation_distance',
            field=models.IntegerField(default=0, verbose_name='فاصله تا حرم (متر)'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='accommodation_type',
            field=models.CharField(choices=[('hotel', 'هتل'), ('hosseinieh', 'حسینیه'), ('apartment', 'آپارتمان'), ('mixed', 'ترکیبی')], default='hotel', max_length=20, verbose_name='نوع اقامتگاه'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='departure_date',
            field=models.CharField(max_length=30, verbose_name='تاریخ حرکت (شمسی)'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='duration',
            field=models.IntegerField(verbose_name='مدت سفر (روز)'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک تصویر'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام مدیر کاروان'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام کاروان'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='محبوب'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='price',
            field=models.IntegerField(verbose_name='قیمت هر نفر (تومان)'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='remaining_capacity',
            field=models.IntegerField(verbose_name='ظرفیت باقیمانده'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='special_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='برچسب ویژه'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='transportation_type',
            field=models.CharField(choices=[('bus', 'اتوبوس'), ('train', 'قطار'), ('airplane', 'هواپیما'), ('combined', 'ترکیبی')], default='bus', max_length=20, verbose_name='نوع حمل\u200cونقل'),
        ),
    ]
