# Generated by Django 5.2.15 on 2026-07-03 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_remove_booking_address_and_more'),
        ('carvans', '0003_caravanphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaravanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن نظرسنجی')),
                ('reviewer_name', models.CharField(blank=True, max_length=100, verbose_name='نام زائر')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز (۰-۵)')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='ثبت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='رزرو')),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='carvans.caravan', verbose_name='کاروان')),
            ],
            options={
                'verbose_name': 'نظر زائر',
                'verbose_name_plural': 'نظرات زائران',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
    ]
