# Generated by Django 4.2.28 on 2026-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvans', '0004_caravanreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='bus_type',
            field=models.PositiveSmallIntegerField(choices=[(25, 'اتوبوس ۲۵ نفره (VIP)'), (32, 'اتوبوس ۳۲ نفره'), (44, 'اتوبوس ۴۴ نفره')], default=44, help_text='برای سفرهای زمینی: تعداد صندلی هر اتوبوس. چیدمان صندلی رزرو بر همین اساس ساخته می\u200cشود.', verbose_name='نوع اتوبوس (ظرفیت هر اتوبوس)'),
        ),
    ]
