# Generated by Django 4.2.30 on 2026-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvans', '0006_caravan_train_type_optional_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='seat_selection_enabled',
            field=models.BooleanField(default=False, help_text='تا وقتی خاموش است، زائر نقشه\u200cی صندلی را نمی\u200cبیند و رزرو بدون شماره\u200cی صندلی ثبت می\u200cشود؛ صندلی\u200cها را خودتان بعداً تخصیص می\u200cدهید. روشن کردنش باعث می\u200cشود هر کسی که فرم را پر کند صندلی را اشغال کند.', verbose_name='انتخاب صندلی توسط زائر'),
        ),
    ]
