# Generated by Django 4.2.30 on 2026-10-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvans', '0007_caravan_seat_selection_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='registration_opens_on',
            field=models.CharField(blank=True, help_text='اختیاری. مثلاً ۱۴۰۵/۰۸/۱۵ — کنار «به\u200cزودی» به زائر نشان داده می\u200cشود.', max_length=30, verbose_name='تاریخ بازشدن ثبت\u200cنام (شمسی)'),
        ),
        migrations.AddField(
            model_name='caravan',
            name='registration_state',
            field=models.CharField(choices=[('open', 'ثبت\u200cنام باز است'), ('soon', 'ثبت\u200cنام به\u200cزودی'), ('closed', 'ثبت\u200cنام بسته است')], default='open', help_text='با «به\u200cزودی» کاروان در سایت دیده می\u200cشود ولی دکمه\u200cی رزرو غیرفعال است.', max_length=10, verbose_name='وضعیت ثبت\u200cنام'),
        ),
    ]
