# Generated by Django 4.2.28 on 2026-02-06 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carvans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_passenger_name', models.CharField(max_length=100)),
                ('main_passenger_id', models.CharField(max_length=20)),
                ('main_passenger_phone', models.CharField(max_length=20)),
                ('main_passenger_birthdate', models.CharField(max_length=15)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('companions', models.JSONField(blank=True, default=list)),
                ('address', models.TextField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('selected_seats', models.JSONField(blank=True, default=list)),
                ('total_price', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('transportation_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carvans.caravan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
