# Generated by Django 4.2.28 on 2026-07-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carvans', '0002_alter_caravan_options_caravan_accommodation_city_and_more'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.AddField(
            model_name='booking',
            name='main_passenger_emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره اضطراری سرپرست'),
        ),
        migrations.AddField(
            model_name='booking',
            name='main_passenger_foreign_lastname',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی انگلیسی سرپرست'),
        ),
        migrations.AddField(
            model_name='booking',
            name='main_passenger_foreign_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی سرپرست'),
        ),
        migrations.AddField(
            model_name='booking',
            name='main_passenger_messaging_apps',
            field=models.JSONField(blank=True, default=list, verbose_name='پیام\u200cرسان\u200cهای سرپرست'),
        ),
        migrations.AddField(
            model_name='booking',
            name='main_passenger_passport_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره گذرنامه سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='caravan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carvans.caravan', verbose_name='کاروان'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='companions',
            field=models.JSONField(blank=True, default=list, verbose_name='همراهان'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_passenger_birthdate',
            field=models.CharField(max_length=15, verbose_name='تاریخ تولد سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_passenger_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد ملی سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_passenger_name',
            field=models.CharField(max_length=100, verbose_name='نام سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_passenger_phone',
            field=models.CharField(max_length=20, verbose_name='شماره موبایل سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد مسافرین'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_seats',
            field=models.JSONField(blank=True, default=list, verbose_name='صندلی\u200cهای انتخابی'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='درخواست\u200cهای خاص'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده'), ('completed', 'تکمیل شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transportation_type',
            field=models.CharField(max_length=50, verbose_name='نوع حمل\u200cونقل'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
