# Generated by Django 4.2.28 on 2026-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_remove_booking_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='کد رزرو'),
        ),
        migrations.AddField(
            model_name='booking',
            name='main_passenger_first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام سرپرست'),
        ),
        migrations.AddField(
            model_name='booking',
            name='main_passenger_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_passenger_birthdate',
            field=models.CharField(blank=True, max_length=15, verbose_name='تاریخ تولد سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_passenger_name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی سرپرست'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='main_passenger_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل سرپرست'),
        ),
    ]
