# Generated by Django 4.2.28 on 2026-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_backfill_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_link',
            field=models.URLField(blank=True, help_text='پس از تأیید نهایی، لینک پرداخت در صفحه رسید زائر نمایش داده می\u200cشود.', max_length=500, verbose_name='لینک پرداخت'),
        ),
    ]
